name: exchange_rate_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  get_it: ^7.2.0
  injectable: ^2.3.2
  auto_route: ^7.8.4
  equatable: ^2.0.5
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.2
  freezed: ^2.3.2
  dio: ^5.2.1
  formz: ^0.6.0
  json_annotation: ^4.8.0
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.1
  shimmer: ^3.0.0
  dartz: ^0.10.1
  retrofit: ^4.0.3
  jwt_decoder: ^2.0.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^7.2.0
  json_serializable: ^6.1.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/l10n/
    - asset/image/lao.png
    - asset/image/china.png
    - asset/image/thai.png
    

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

